### ISSUE TITLE
Aircraft sometimes wont climb and can't handoff to center

### ISSUE THREAD

**Issue by golfyplayz** [mmp/vice#108]
I've only seen this happen on the new M98 scenario, but sometimes I'll tell planes to climb to 170, and they'll start, but then they'll be at 3000 at the border, and this only happens with some. Also, when I flash the planes to center, they never accept the handoff, it just keeps flashing to them.

**Comment by checkandmate1** [comment]
They seem to be working fine for me. What configuration are you on?

**Comment by golfyplayz** [comment]
they are all climbing now, but center still doesnt accept the handoffs

**Comment by golfyplayz** [comment]
I figured out the problem. some of MSP's sids have climb restricions, and whoever made the scenario had the aircraft cross them at like 4000 or 5000 instead of above

**Comment by checkandmate1** [comment]
Ok cool. How are you handing off the ac?

**Comment by golfyplayz** [comment]
center still isnt accepting it

**Comment by checkandmate1** [comment]
What command are you entering?

**Comment by golfyplayz** [comment]
ive tried c, c05 neither of them work

**Comment by golfyplayz** [comment]
it shows that its flashing to them

**Comment by checkandmate1** [comment]
So the M98 file hasn't been updated for the new STARS stuff. So it won't work until it's updated

**Comment by golfyplayz** [comment]
where do I need to update it? i'm working on adding 17/35 and updating some of the file organization

**Comment by checkandmate1** [comment]
Wait, it shouldn't be flashing. At least its not for me. Which version of _vice_ are you running? For me it's going into the scratchpad

**Comment by golfyplayz** [comment]
i think im running the beta whatever. I have the new menu gui, and the new scenarios

**Comment by checkandmate1** [comment]
When is the last time you have downloaded it?

**Comment by golfyplayz** [comment]
recently. I think I see what im doing, i think I am putting it into the scratch pad. how do I hand off then? this is what ive been doing so I guess I'm just used to it

**Comment by checkandmate1** [comment]
The file hasn't been updated. So it will not work

**Comment by golfyplayz** [comment]
ok. where do I have to update it?

**Comment by checkandmate1** [comment]
You can find the relevant information in [this Discord announcement](https://discord.com/channels/1090685318014976081/1218838600804728952/1218973499280986173). The docs will be updated shortly. (Note: All files have been updated, so that announcement only applies to new files being made.)

**Comment by checkandmate1** [comment]
Let me know if this bug persists now.
