### ISSUE TITLE
add a facility engineering FAQ to the documentation

### ISSUE THREAD

**Issue by mmp** [mmp/vice#109]
- How do I get started
- How do I test my edits
- How do I submit a scenario or updated scenario
- it says "center" is unknown even though it's in the documentation (brace nesting)
- how do I get the lat-longs of a point on the map

**Comment by mmp** [comment]
- vice exits immediately with my new scenario. why? a: run it from the command line so you can see the error output

**Comment by checkandmate1** [comment]
How far are we on completing this? I can work on it if needed.

**Comment by mmp** [comment]
Go for it if you want to! I just pushed some updates to the introductory part of the docs and will only be making changes to the STARS docs for now, so there shouldn't be any conflicts if you're working in the Facility Engineering section.

**Comment by checkandmate1** [comment]
Great, I'll start to add some more stuff to it.
