### ISSUE TITLE
Scrolling is choppy

### ISSUE THREAD

**Issue by checkandmate1** [mmp/vice#111]
With the update, when scrolling with the scroll wheel, the movement is very choopy.

**Comment by mmp** [comment]
Is it better if you change `movementScale = 2` to 1 around line 7106 of stars.go? I tried to make the scrolling less sensitive since I find it to be quite twitchy with my trackpad, but maybe that is a bad idea for mouse scrolling.

**Comment by checkandmate1** [comment]
Interesting. I use a trackpad and it always worked fine for me. Setting `movementScale` to 1 helped, but it still feels a bit choppy.

**Comment by checkandmate1** [comment]
Is this issue caused by switching from floats to ints?

**Comment by mmp** [comment]
Quite possibly. So then this is a philosophical question since this mouse-wheel zoom doesn't have a RW counterpart, I think. Should we still enforce integer-valued ranges for it, or just allow them to be whatever and don't show the decimal, if any, in the DCB?

**Comment by checkandmate1** [comment]
I think changing it to afloat, and just only showing the integer part of it in the DCB is the way to go. Just because it feels so awkward trying to scroll with the values being stored as ints

**Comment by mmp** [comment]
Just pushed a fix for this in da2d67a6201acba3b5e21339d26738e40abe8c55. Now it's smooth with the mouse wheel but the DCB still goes in 1 mile steps (which is, I assume how real world STARS works.) Nevertheless, the DCB always shows an integer-valued range.
