### ISSUE TITLE
History trail overlaps datablock

### ISSUE THREAD

**Issue by checkandmate1** [mmp/vice#112]
<img width="322" alt="Screenshot 2024-03-16 at 2 39 23 PM" src="https://github.com/mmp/vice/assets/133938003/b82a2518-fd0f-4e8f-be35-072d9c328578">

**Comment by mmp** [comment]
I bet that's a regression from 064b789251e0181d98550efa195394d1bbcf046c. The problem I think is that the leader line and datablock are drawn in the same method and I moved that to be before the tracks are drawn while before it was after.

So the right fix is probably to pull out the leader line drawing and then draw things in order
1. leader line
2. radar tracks
3. datablock
