### ISSUE TITLE
<RNGRING> keybind does not allow for numerical entry

### ISSUE THREAD

**Issue by svalencia014** [mmp/vice#116]
According to CRC docs, you can use the <RNGRING> (cntl + f9) to enter a numerical range ring value using the following syntax: `<RNGRING>(2,5,10,20)<ENTER>`

**Comment by mmp** [comment]
Thanks for reporting. Amusingly we have the code to let you enter those values but seem to be missing the code that notices ctrl-F9 and interprets that as `<RNGRING>`. Should be an easy fix. https://github.com/mmp/vice/blob/6898b7c507cbc81e4a0e984c858e132944364802/stars.go#L2980

**Comment by svalencia014** [comment]
The weird thing is using ctrl-F9 activates the range ring DCB button, it just doesn't allow numerical entry.
