### ISSUE TITLE
Coordination lists

### ISSUE THREAD

**Issue by checkandmate1** [mmp/vice#118]
Add coordination lists. Manual 2-91

**Comment by checkandmate1** [comment]
I just got some more information on this:
1. Towers have very different rules for launching departures:
![image](https://github.com/mmp/vice/assets/133938003/d1a3ba3c-ce12-487d-8f5a-9d2c658ba384)
"ABC uses rundown and radar need to accept the request before IFR or VFRs depart.
DEF doesn't use a rundown list so they need to 'verbally' coordinate and get approval for each IFR departure but not VFRs.
XYZ uses the rundown list to give radar the departure sequence/rolling call etc but they don't need to get approval" 
2. An example coordination list would look something like this: 
```
.     PBED
1   N12345 C172  BOX   H270
```
PBED is the list name (not 100% sure what this is). Then, you have N12345 going to BOX, with the list remarks saying he's heading 270. The `1   N12345 C172  BOX   H270` would flash white until the radar controller does `F13 (optional ACID/BCN) ENTER`. After it was accepted, `1   N12345 C172  BOX   H270` would turn to a solid green color and show as 
`1   +N12345 C172  BOX   H270`. The + means the message was accepted. There will probably need to be some work done to how lists are made, just because some times, one line may be a flashing white while the rest of the list is green.

**Comment by mmp** [comment]
Done in aa0fc3d3b3df69c16dbd3a1d80e6f0e8346e3538
