### ISSUE TITLE
LIB Scenarios have incorrect altitude for some flight plans.

### ISSUE THREAD

**Issue by checkandmate1** [mmp/vice#130]
Example flightplan in the LIB scenario:
```json
{
          "airlines": [
            {
              "icao": "JBU"
            }
          ],
          "altitude": 360,
          "destination": "KPBI",
          "exit": "WHITE",
          "route": "ELVAE COL WHITE J209 VILLS J209 SBY J79 KATZN ISO J121 CHS CAKET Q97 DEBRL Q97 MALET DDANY STOOP"
        }  
```
The altitude is 360, which causes a lot of issues, both with it's climbing and the airspace awareness rules. Along with changing the individual scenario, also adding something that checks the altitude in `spawnAircraft()` in sim.go, that if the altitude is less than 1000, it will multiply its altitude by 100.

**Comment by mmp** [comment]
Fixed in 1793945a581e4601dfdfe92734337e83c7ba07e6
