### ISSUE TITLE
Update faclity TCPs + configs

### ISSUE THREAD

**Issue by svalencia014** [mmp/vice#134]
Mainly opening this issue to track my progress converting these files to the new format mentioned by @checkandmate1, in addition to making each sectors TCP ID make sense. 

- [x] A80
- [x] A90
- [x] AAC
- [x] ABE
- [x] ASE
- [x] BHM
- [x] BUR
- [x] CLT
- [x] COS
- [x] CYS
- [x] D01
- [x] D10
- [x] DAB
- [x] DCA
- [x] F11
- [x] GJT
- [x] GSP
- [x] IND
- [x] JAX
- [x] L30
- [x] MKE
- [x] NCT
- [x] ONT
- [x] P50
- [x] PHL
- [x] S46
- [x] SAN
- [x] SAV
- [x] SCT (LAX Area)
- [x] SDF
- [x] SNA
- [x] TPA

**Comment by mmp** [comment]
(I assume you're aware, but make sure you're using the latest scenario files from the master branch for a starting point these changes since they include other recent updates with things like "center", "stars_maps", "inhibit_ca_volumes" being moved under "stars_config".)

**Comment by checkandmate1** [comment]
On top of this, we should probably also use this thread to see which facilities have stars customized, with airspace awareness and whatnot. @svalencia014 @mmp, does this sound good?

**Comment by svalencia014** [comment]
I'm adding airspace awareness as a part of my "modernization" of TRACONs with proper TCPs

**Comment by mmp** [comment]
Took care of a bunch of these in 02062f7f0fabe6fc42580de1152fca80455a8de8. (And will plan to knock off more in the coming days.)

**Comment by mmp** [comment]
I believe these are all done now but would welcome a second pair of eyes so won't close this yet.

**Comment by mmp** [comment]
Closing this out; any that are missing / wrong we can treat as a new bug.
