### ISSUE TITLE
STARS: should issue an error if we attempt to hand off to ourself

### ISSUE THREAD

**Issue by mmp** [mmp/vice#150]
Currently the track starts flashing, etc., like a regular handoff. (TODO: double check what the STARS manual says about this.)

**Comment by checkandmate1** [comment]
I did this for quicklooks in #30, but I suppose handoffs/ pointouts should have this as well. Do you think this logic should live in `calculateController` or the respective method?

**Comment by mmp** [comment]
Probably not `calculateController` since I could imagine cases where it would be legit to get our own TCP ID from a `calculateController` lookup. I think it probably should be a check in `Sim`. (In general, it's good to have those sorts of checks there since it has the true view of the `World`. On the client side, the `World` may be slightly out of date due to other controllers' actions changing the `World` before we get an update. That's likely not an issue in this case, but in general it's good to do validation sorts of checks like this there..)

**Comment by checkandmate1** [comment]
Sounds great
