### ISSUE TITLE
Toggle between STARS/simulation command modes?

### ISSUE THREAD

**Issue by catcarbon** [mmp/vice#152]
With the addition of new STARS commands, command processing is becoming more complicated because of simulation commands with similar syntax. I wonder if using a key like Caps Lock to toggle between STARS/simulation command mode would help simplify and disambiguate command processing.

I also considered a separate command window but using a toggle key has the following advantages:
1. No need to code for a separate command window and deal with switching window focus.
2. Creates the least disruption to player workflow.

**Comment by mmp** [comment]
Done in the latest release (with TAB or clicking the window) to switch between STARS and a CLI in the bottom window.
