### ISSUE TITLE
inter-facility handoff not working

### ISSUE THREAD

**Issue by mmp** [mmp/vice#155]
If I start a KEWR scenario and enter `Δ1A` and slew to hand off to ABE_APP, nothing happens: the command is accepted without an error but the handoff never happens, nothing shows up in the datablock to indicate an outbound handoff, etc.

**Comment by checkandmate1** [comment]
∆1A shouldn't work from N90 to ABE. The correct syntax would be ∆4 or ∆41A/D. 1 is the facility identifier for PVD AFAIK; however, that's weird about how it does nothing. Was it inputted to the scratchpad?

**Comment by checkandmate1** [comment]
I am seeing it now. It does nothing, it should input that into the scratchpad.
