### ISSUE TITLE
Rework list/ datablock drawing

### ISSUE THREAD

**Issue by checkandmate1** [mmp/vice#161]
This is a prerequisite to #128 and #118, as the secondary SPC warnings are drawn as yellow, while on the same line as the primary SPC warnings (red). And for the coordination lists, some lines of that list are drawn in a flashing white, while others are a steady green.

**Comment by mmp** [comment]
Closing this out as the new(ish) datablock code now supports arbitrary color values specified per-character. (And the coord list stuff is in there.)
