### ISSUE TITLE
Fix live weather

### ISSUE THREAD

**Issue by checkandmate1** [mmp/vice#168]

**Comment by mmp** [comment]
Not sure if it's overkill but using something like https://github.com/urkk/metar for the METAR parsing could be worthwhile.

**Comment by checkandmate1** [comment]
What only parses a METAR, it doesn't get you the METAR from an ICAO code correct?

**Comment by mmp** [comment]
Yes, I believe so.

**Comment by checkandmate1** [comment]
The only METAR parsing that is going on is finding the altimeter. (For some reason it's in HPA and not INHG). I don't think there is a reason to parse the already parsed METAR. If I'm overlooking something please let me know!

**Comment by mmp** [comment]
Ah, got it, sorry. I was thinking the crash was from parsing the wind from the METAR. So nevermind..
