### ISSUE TITLE
Fix sequencing challenge

### ISSUE THREAD

**Issue by checkandmate1** [mmp/vice#201]
It's been really bugging me when there are multiple of the same departure gates in a row, so this will add a cap to the amount of same-gate departures

**Comment by radarContacto** [comment]
Not sure how it’s coded but some things that can make departure sequencing challenging are:

1) Miles-in-trail restrictions (the user could simulate this themselves)

2) When a tower gives you close to minimum separation on departures and you have to increase the interval before handing off to ARTCC.

3) Tower gives you close spacing with disimilar aircraft. If the facility isn’t procedurally constructed  you can have a challenging time getting your in-trail to ARTCC. 

4)Weather deviations - we just depict precip on the scopes. Many times ppl start asking for deviation for buildups and you have to make a mental picture of what’s going on. 

5) Sequencing multiple departures from different airports to same fix. Some facilities are not allowed to stack departures and have to put everyone in trail. 

6) At smaller class C, missing IFRs with random VFRs flying around that always seem to find the worst location/altitude to fly around at.
