### ISSUE TITLE
Vice WON"T open

### ISSUE THREAD

**Issue by VVESM4N** [mmp/vice#21]
I just downloaded the software today. I closed out of it earlier and now I can't open it. When I double click it and try to open it with administrator, it logs on on the taskbar below and shows it is open but can't see it on my screen even when I click on it. I operate Windows 11. 

![viceidk](https://github.com/mmp/vice/assets/156626877/5c61779b-6685-4f4a-a1ca-da2932c23110

**Comment by mmp** [comment]
Strange! Try going to your `%APPDATA%` folder and finding the Vice folder in there (I think it's under the roaming profiles one but can't remember for sure.) Then delete the `config.json` file you find in there and try restarting vice. Let me know if that helps.

**Comment by VVESM4N** [comment]
It now opens but now wants me to download a new update and the update won't download due to me "not trusting the download" and needs to have my trust.

**Comment by mmp** [comment]
Yes, unfortunately signing Windows apps is challenging and so vice is unsigned. You will have to trust it if you want to run it.
