### ISSUE TITLE
Redirect handoff fixes

### ISSUE THREAD

**Issue by mmp** [mmp/vice#214]
[discord](https://discord.com/channels/1090685318014976081/1240518110604427355/1240518110604427355)

How it should be:

1) You can't redirect to an interfacility position (outside your local STARS system) - ILL TRK. Right now on Vice, I can redirect to an external facility. 

2) You can't redirect to the controller who initiated the handoff - ILL POS.

3) If redirected, the position symbol of who the handoff has been redirected to should display. I keep seeing "R" an "P" on Vice when that is not the position id of whom it has been redirected. 

4) When redirected handoff is accepted, "RD" only remains at the original local handoff initiator for around 30sec or until clicked. "RD" is removed immediately  from tag at the position that accepted the handoff and the position that redirected the handoff.

5) If your position is not involved in a redirect (if you're not the originator, redirector, or redirected receiver), you will not see "RD" in the tag and it will apear as a normal handoff to you.

Note: This is site adaptable so might be slightly different between facilites. E.g., some facilites allow redirect but do not show the indicator. The above description is how it works at most places though.

**Comment by excile1** [comment]
Since #223 was merged, this issue can be closed @mmp
