### ISSUE TITLE
more scratchpad bugs

### ISSUE THREAD

**Issue by mmp** [mmp/vice#242]
[discord](https://discord.com/channels/1090685318014976081/1238599672944398357/1247691780007395379)

> I ran a P50 session and noticed an issue: Vice doesn't allow me to enter single char scratch pads even if I do MF, Y. STARS allows you to put in single char scratchpads especially if you do MF, Y command. I was trying to input "8" and "R"...stuff like that and I got "FORMAT" on Vice. If you try to put three digits into SCR1 it is interpreted as pilot reported altitude (if not receiving mode-c, otherwise you'd get "ILL FNCT" if you were receiving mode-c and it hadn't been disabled). 
>
> Also, If I type "08" or "I8" and go to click on target, it gives me "FORMAT".  I should be able to type two chars and click on the target without having to do MF, Y, cc click. (As long as the two chars do not represent a subset and position for handoff code).

**Comment by radarContacto** [comment]
Another issue I've seen on Vice is if the facility file allows for 4-char scratch pads, Vice will not let me manually enter a 4-char scratch pad. In RW (most facilities I've seen) if you try to a 4-char SCR1 the implied way, you'll actually replace the aircraft type, so you'd have to do MF, Y, 4-char, click to enter it to not replace aircraft type (for SCR1). The implied "+" for SCR2 should still work with 4-chars if the site has 4-char scratch enabled. Many places use this to show where an aircraft is direct to, climbing/descending to/ assigned.

**Comment by radarContacto** [comment]
I am still unable to do MF, Y, single-char on Vice. SCR2 single-char seems to work though! For example, @P50, "L" means the aircraft is executing visual approach to the left runway (25L or 07L).

**Comment by mmp** [comment]
All of the above are (I believe!) fixed for the next release.
