### ISSUE TITLE
Simultaneous TPA and JRING

### ISSUE THREAD

**Issue by checkandmate1** [mmp/vice#263]
P cones and J rings cannot be simultaneous, it's one or the other.

**Comment by mmp** [comment]
(per 6-163 it looks like **A**TPA cones and J-rings can both be displayed for a track, so when this is fixed we should be careful to still allow that.)

**Comment by radarContacto** [comment]
> (per 6-163 it looks like **A**TPA cones and J-rings can both be displayed for a track, so when this is fixed we should be careful to still allow that.)

I confirm this is correct.
