### ISSUE TITLE
Add callsign filter

### ISSUE THREAD

**Issue by lightbord** [mmp/vice#3]
Add a filter for bad call signs. Today Vice generated AAL11. Suggest blocking all calls signs of terrorist attacks and major deadly incidents.

![Screenshot 2023-05-05 010149 aal11](https://user-images.githubusercontent.com/28508844/236381125-03a13e3b-0324-48d1-8f72-f39e7e0407e2.png)

**Comment by mmp** [comment]
Awkward. Thanks for flagging that.

Fixed now. I'll get an updated release out in a day or two.
