### ISSUE TITLE
Problem when launching - not enough room in 32 bits 

### ISSUE THREAD

**Issue by iassots** [mmp/vice#308]
I downloaded Vice from the website and installed it. The problem is that I can not launch it. Everytime I open Vice, there is this error: not enough room in 32 bits. I´m not a computer expert, but I would love to play it.

Thanks for your help.
![Screenshot 2024-08-05 152536](https://github.com/user-attachments/assets/3a88ce10-64f2-438e-a767-bb3bb76ed578)

**Comment by mmp** [comment]
Ah, interesting. I think I see the issue. Will try to fix this soon.

**Comment by mmp** [comment]
Thanks for reporting this!

**Comment by iassots** [comment]
Thanks. Appreciate your help

**Comment by mmp** [comment]
This should be fixed for the next release. You can try the build here if you like: https://github.com/mmp/vice/actions/runs/10275907207

(Note that you won't be able to connect to multi-controller but can at least use it single controller until the next official release goes out.)
