### ISSUE TITLE
Add BDL RWY 6 Scenario

### ISSUE THREAD

**Issue by pigcodes29** [mmp/vice#31]
BDL RYW 6 Scenario, **not as in depth as others**

_Completed:_ 
      RWY 6 departures (BDL6 Departure)
      ILS 6 arrivals

_In development (in order of priority):_
     RWY 33 Departures 
     ILS 33 arrivals
     24/15 Dep/Arr

(Apologies if this is not the right way to submit somthing) 
[bdl (1).json](https://github.com/mmp/vice/files/14517158/bdl.1.json)

**Comment by checkandmate1** [comment]
In the future, you can use the [_vice_ discord](https://discord.gg/y993vgQxhY)

**Comment by mmp** [comment]
Looks good! I'll add it for the next release. How do you want to be listed in the credits?

One thing I noticed is that you're missing the procedure turn for the ILS 6 (and the waypoints after PENNA, though thouse are less important). It should look something like:

```
PENNA/a3000+/lhilpt/pta3000/iaf JANID/a2400+ HUNEE/a1800+
```

So it's got a hold-in-lieu of procedure turn with left turns, aircraft should come in at or above 3000, and should exit the PT at 3000. (And PENNA is the IAF). (Similarly for the ILS 24).

If you run vice from the command-line and add `-routes KBDL` it will print out all of the routes it knows about from the FAA coded instrument flight procedures (CIFP) and you can reference those in your scenario files. So you could write just this for the approaches:

```
            "approaches": {
                "I6": { "cifp_id": "I6" },
                "I24": { "cifp_id": "I24" }
            },
```

and vice will get them from the CIFP. I've gone ahead and made that change in the version you sent me but just so you know for the future.

**Comment by pigcodes29** [comment]
Thanks for the advice! If you could credit me as "MerryArbitrary" that
would be great. I will send any further updates to you on discord.
