### ISSUE TITLE
bug: aircraft descend along approach when only told to intercept localizer

### ISSUE THREAD

**Issue by yourcptainspeaking** [mmp/vice#392]
Aircraft will descend along the approach path when told to intercept the localizer via the "[CALLSIGN] I" command. I've only tested this at AUS but I doubt its scenario based

**Comment by mmp** [comment]
Interesting! I'm having trouble reproducing this: can you send an exact recipe to reproduce it? e.g., I tried with the AUS South scenario, vectored a few aircraft to 18L, descended to 4,000 and intercepted between SCALI and DOFFS (trying from both sides), and they stayed at 4,000 all the way in.

**Comment by yourcptainspeaking** [comment]
> Interesting! I'm having trouble reproducing this: can you send an exact recipe to reproduce it? e.g., I tried with the AUS South scenario, vectored a few aircraft to 18L, descended to 4,000 and intercepted between SCALI and DOFFS (trying from both sides), and they stayed at 4,000 all the way in.

Keep the aircraft at 5000 and intercept them around LAMAS for 36L. I've never tested if they descend all the way down but I know they'll at least start descending to cross CAMDY at 4000 rather than maintaining the assigned altitude

**Comment by mmp** [comment]
Unfortunately I'm still unable to reproduce this; I just had 5 intercept the 36L localizer and all stayed at 5,000 all the way in. Do you see this happen for all aircraft? Only ones on certain arrivals?

**Comment by yourcptainspeaking** [comment]
It seems to only happen when the 5000 foot altitude is the result of a restriction on the STAR (possible the way these restrictions are handled causes them to continue descending via the approach path). I just reproduced it using the LAIKS3 arrival and runway 36R if that helps

**Comment by mmp** [comment]
This should be fixed now for the next release. (Fixing this surfaced another few bugs related to aircraft told to intercept but not cleared, so I'm happy to have this tuned up.)
