### ISSUE TITLE
allow configuring the [TGT GEN] key

### ISSUE THREAD

**Issue by mmp** [mmp/vice#413]
Evidently `;` is a pain to enter on European keyboards.

**Comment by checkandmate1** [comment]
@mmp, what keys should be available to be binded? It doesn't seem like there are many useful options; I can't think of any useful ones besides tab and the semi-colon.

**Comment by mmp** [comment]
Comma might be good, per https://discord.com/channels/1090685318014976081/1090685318459559937/1300044647523029022. (And that isn't allowed in scratchpads, thankfully.)

I was thinking maybe we should go ahead have a little UI to set the bindings for all of the STARS command keys. We already have `\` hard-coded as an alternative for `[MIN]` (typically the Home key); maybe we should just put all of that in users hands, with the current bindings the defaults.

**Comment by checkandmate1** [comment]
I'll add in the comma. Tab is also used for the messages pane, which now doesn't have much of a use. What'd be your idea for implementing tab for aircraft commands (I generally prefer tab over the semicolon or any other key)?

**Comment by mmp** [comment]
@checkandmate1 the last remaining reason to tab to the messages pane is for the `/` command for group chat. I do like the idea of having the messages pane just show informational messages at this point (and I like the idea of deleting the code related to keyboard input and "which pane has focus".) However, moving the chat functionality to STARS seems a little messy with its whole start a new line each time space is entered way of laying out the input. Any thoughts/opinions?
