### ISSUE TITLE
add hold for release / uncontrolled field operations

### ISSUE THREAD

**Issue by mmp** [mmp/vice#65]
Some discussion of the issues here: https://discord.com/channels/1090685318014976081/1179784230654455859/1179784230654455859

Related: 2-91 in the STARS manual on coordination lists

**Comment by checkandmate1** [comment]
I started working on this. Should be done soon

**Comment by mmp** [comment]
Also related p4-91 audio notifications for departure releases

**Comment by checkandmate1** [comment]
I'll take a look

**Comment by checkandmate1** [comment]
@mmp adding in the sound effect will need it's own feature request. "Coordination lists". I'll make the issue

**Comment by mmp** [comment]
aa0fc3d3b3df69c16dbd3a1d80e6f0e8346e3538
