### ISSUE TITLE
add IsArrival to Aircraft?

### ISSUE THREAD

**Issue by mmp** [mmp/vice#71]
Currently aircraft are basically either departures or arrivals. We have `Aircraft` `IsDeparture()` and numerous places in the code use `!IsDeparture()` to check "is it an arrival?".

Yet, we should be able to have an KFRG departure that is a KHVN arrival, all under the control of a single controller in a session. This may all just work as things are implemented, though I suspect that there are enough assumptions that an aircraft is one or the other (but not both) that something would break if we had one.

**Comment by radarContacto** [comment]
Not sure how helpful this is but: In rw when designing a facility file there is a section of the file that has parameters for airports. One parameter is "Local Arrival". It is meant to indication if an airport is a local arrival airport. If it is, then any departure flight plan that has the airport as its exit fix is automatically changed to an arrival flight plan when the flight is initially acquired on radar. 

It would also be **EXTEMLY** helpful to allow type "Overflight". Without overflights, I am unable to simulate anywhere from 25-70% of some facilities traffic. 

If I can be of any help, please let me know!
