### ISSUE TITLE
figure out what WX contrast is supposed to do

### ISSUE THREAD

**Issue by mmp** [mmp/vice#99]
The BRITE menu includes both "WX" for weather brightness and "WXC" for weather contrast. We don't currently handle WXC. It's not immediately clear what effect WXC should have. Increase/decrease the saturation of the colors independent of brightness?

**Comment by checkandmate1** [comment]
According to an IRL controller, our weather radar is wrong. It goes as follows:
```
ASR radars show 6 intensities. It’s just to distinguish which level of weather it is
Light green with no dots is level 1
Green with wide dots level 2
Green with close dots 3
Mustard 4
Mustard wide dots 5
Mustard tight dots 6
```
The controller has a video but said that it shouldn't be put in a public issue. He said it's fine if I send it to @mmp
